language: php
php:
  - 5.6
  - 7.0
  - 7.1

branches:
    only:
        - master
        - /^greenkeeper-.*$/

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - travis_retry nvm install node
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction
    - travis_retry npm install
    - cp .env.example .env
    - php artisan key:generate

before_script:
    - npm prune
    - sleep 5

script:
    - composer run phpunit -- --verbose
    - composer run phpcs
    - composer run phpmd
    - npm run unit
    - npm run lint

after_success:
    - npm run report-coverage
